/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul6;

/**
 *
 * @author Luviana
 */
public class form_pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form form_pembayaran
     */
    public form_pembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBrg1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBrg2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBrg3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBrg4 = new javax.swing.JTextField();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();
        btnProses1 = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 310, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Harga Barang 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(5, 70, 110, 30);

        txtBrg1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtBrg1);
        txtBrg1.setBounds(130, 70, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Harga Barang 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(5, 120, 110, 30);

        txtBrg2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtBrg2);
        txtBrg2.setBounds(130, 120, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Harga Barang 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(5, 170, 110, 30);

        txtBrg3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBrg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrg3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtBrg3);
        txtBrg3.setBounds(130, 170, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Harga Barang 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(5, 220, 110, 30);

        txtBrg4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBrg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrg4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtBrg4);
        txtBrg4.setBounds(130, 220, 150, 30);

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(220, 320, 75, 30);

        Hasil.setColumns(20);
        Hasil.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 370, 240, 120);

        btnProses1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnProses1.setText("Proses");
        btnProses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProses1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses1);
        btnProses1.setBounds(20, 320, 75, 30);

        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus);
        btnHapus.setBounds(120, 320, 75, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Diskon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(5, 270, 110, 30);

        txtDiskon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiskonActionPerformed(evt);
            }
        });
        getContentPane().add(txtDiskon);
        txtDiskon.setBounds(130, 270, 150, 30);

        setBounds(0, 0, 331, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBrg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrg3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrg3ActionPerformed

    private void txtBrg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrg4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrg4ActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnProses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProses1ActionPerformed
        // TODO add your handling code here:
        
        int barang1 = Integer.parseInt(txtBrg1.getText());
        int barang2 = Integer.parseInt(txtBrg2.getText());
        int barang3 = Integer.parseInt(txtBrg3.getText());
        int barang4 = Integer.parseInt(txtBrg4.getText());
        int diskon = Integer.parseInt(txtDiskon.getText());
        
        int total_harga = barang1 + barang2 + barang3 + barang4;
        int total_bayar = total_harga - (total_harga * diskon / 100);

        Hasil.setText("Harga Barang 1 : " + barang1 + "\nHarga Barang 2 : " + barang2 + "\nHarga Barang 3 : " + barang3 
                + "\nHarga Barang 4 : " + barang4 + "\nDiskon Anda : " + diskon + "\nTotal Harga : " + total_harga 
                + "\nTotal Bayar : " + total_bayar);
    }//GEN-LAST:event_btnProses1ActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        txtBrg1.setText("");
        txtBrg2.setText("");
        txtBrg3.setText("");
        txtBrg4.setText("");
        txtDiskon.setText("");
        Hasil.setText("");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiskonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Hasil;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnProses1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBrg1;
    private javax.swing.JTextField txtBrg2;
    private javax.swing.JTextField txtBrg3;
    private javax.swing.JTextField txtBrg4;
    private javax.swing.JTextField txtDiskon;
    // End of variables declaration//GEN-END:variables
}
